//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaWebAPI.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class firma2Entities : DbContext
    {
        public firma2Entities()
            : base("name=firma2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Firma> Firma { get; set; }
        public virtual DbSet<Opstina> Opstina { get; set; }
        public virtual DbSet<ViewFirme1> ViewFirme1 { get; set; }
        public virtual DbSet<Racun> Racun { get; set; }
    
        public virtual ObjectResult<procFirme_Result> procFirme()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<procFirme_Result>("procFirme");
        }
    }
}
