//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFirme1
    {
        public int ID { get; set; }
        public string Naziv { get; set; }
        public string Adresa { get; set; }
        public string JIB { get; set; }
        public string PDVBroj { get; set; }
        public string Opstina { get; set; }
    }
}
