CREATE TABLE [dbo].[Racun](
	[ID] [int] NOT NULL,
	[Datum] [date] NOT NULL,
	[Iznos] [decimal](18,0) NOT NULL,
	[FirmaID] [int] NOT NULL,
CONSTRAINT [PK_Racun] PRIMARY KEY CLUSTERED 
	( ID ASC )
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Racun] WITH CHECK ADD CONSTRAINT [FK_Racun_Firma] FOREIGN KEY([FirmaID])
REFERENCES [dbo].[Firma] ([ID])
GO

ALTER TABLE [dbo].[Racun] CHECK CONSTRAINT [FK_Racun_Firma]
GO